#!/usr/bin/env node
/**
 * Ancestors: reduce the cached gallery responses (fetch-plates.mjs) to the data
 * file the page imports, and measure every cover so tiles can keep the scan's
 * own proportions.
 *
 *   node scripts/ancestors/build-plates.mjs
 *
 * Writes src/data/library-plates.ts. Generated: do not edit it by hand.
 * Captions are the library's own `description` for each extracted image.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const cache = path.join(root, "node_modules/.cache/ancestors-plates");
const PER_BOOK = 6;

/**
 * Pages pinned to the front of a book's list, in this order. These are the
 * figures the notes are actually about (Llull's wheels, Huygens' wavelets), which
 * the library's quality score has no way to know.
 */
const PIN = {
  "695592c17bd6d2cd1d61afec": [40, 36, 39],
  "6953e58d77f38f6761bf0cfc": [27, 56, 29, 72],
  "69dbcac31040d1d5e20ae6df": [6, 7],
};

const shelf = fs.readFileSync(path.join(root, "src/data/library-shelf.ts"), "utf8");
const books = [...shelf.matchAll(/^\s{4}id: "([0-9a-f]{24})",[\s\S]*?^\s{4}thumbnail: "([^"]+)",$/gm)].map(
  (m) => ({ id: m[1], thumbnail: m[2] }),
);

/** Initials and printers' ornaments are real, but they are not what a reader comes for. */
const rank = (it) => {
  const d = `${it.type} ${it.description}`.toLowerCase();
  let s = (it.galleryQuality ?? 0.5) + (it.confidence ?? 0.5) * 0.2;
  if (/diagram|engraving|illustration|map|chart|figure|plate/.test(it.type ?? "")) s += 0.3;
  if (/\binitial\b|ornament|printer's (mark|device)|headpiece|tailpiece|vignette|border/.test(d)) s -= 0.8;
  if (it.type === "decorative") s -= 0.4;
  if (it.aspect < 0.3 || it.aspect > 3.2) s -= 0.3;
  return s;
};

const plates = {};
let kept = 0;
for (const { id } of books) {
  const file = path.join(cache, `${id}.json`);
  if (!fs.existsSync(file)) continue;
  const pins = PIN[id] ?? [];
  const pinned = (it) => (pins.includes(it.pageNumber) ? pins.indexOf(it.pageNumber) : -1);
  const items = (JSON.parse(fs.readFileSync(file, "utf8")).items ?? [])
    .filter((it) => it.extractedUrl && it.aspect)
    .filter((it) => pinned(it) >= 0 || rank(it) > 0.55)
    .sort((a, b) => {
      const pa = pinned(a);
      const pb = pinned(b);
      if (pa >= 0 || pb >= 0) return pa < 0 ? 1 : pb < 0 ? -1 : pa - pb;
      return rank(b) - rank(a);
    })
    .slice(0, PER_BOOK);
  if (!items.length) continue;
  plates[id] = items.map((it) => ({
    src: it.extractedUrl,
    thumb: it.thumbnailUrl ?? it.extractedUrl,
    aspect: Math.round(it.aspect * 1000) / 1000,
    page: it.pageNumber,
    kind: it.type ?? "image",
    caption: it.description,
  }));
  kept += items.length;
}

/**
 * The library keeps a 150px rendition beside most page scans. Fifty full scans
 * are about 48 MB, which is no way to open a page, so the field uses these and
 * the full scan is fetched only for the book being read.
 */
const smallOf = (u) => {
  let m = u.match(/\/archived\/([0-9a-f]+)\/(\d+)\.jpg$/);
  if (m) return `https://images.sourcelibrary.org/pages/${m[1]}/${m[2].padStart(4, "0")}-thumb.jpg`;
  m = u.match(/\/pages\/[0-9a-f]+\/\d+\.jpg$/);
  return m ? u.replace(/\.jpg$/, "-thumb.jpg") : null;
};

const aspects = {};
const small = {};
for (const { id, thumbnail } of books) {
  const candidate = smallOf(thumbnail);
  if (candidate) {
    try {
      const head = await fetch(candidate, { method: "HEAD", signal: AbortSignal.timeout(30_000) });
      if (head.ok) small[id] = candidate;
    } catch {
      /* no small rendition: the tile falls back to the full scan */
    }
  }
  try {
    const res = await fetch(thumbnail, { signal: AbortSignal.timeout(60_000) });
    const meta = await sharp(Buffer.from(await res.arrayBuffer())).metadata();
    aspects[id] = Math.round((meta.width / meta.height) * 1000) / 1000;
  } catch (err) {
    console.log("cover not measured", id, String(err).slice(0, 80));
  }
}

const out = `/**
 * GENERATED by scripts/ancestors/build-plates.mjs. Do not edit by hand.
 *
 * SHELF_PLATES: illustrations the Source Library has extracted from each book's
 * scans, best first. Captions are the library's own descriptions. Books the
 * library has extracted nothing from are simply absent.
 * SHELF_COVER_ASPECT: width / height of each cover scan, so a tile can show the
 * page whole instead of cropping it to a common shape.
 * SHELF_COVER_SMALL: a light rendition of the cover for the field of tiles.
 */

export interface ShelfPlate {
  src: string;
  thumb: string;
  /** width / height of the extracted image */
  aspect: number;
  /** page of the scan it was taken from */
  page: number;
  kind: string;
  caption: string;
}

export const SHELF_PLATES: Record<string, ShelfPlate[]> = ${JSON.stringify(plates, null, 2)};

export const SHELF_COVER_ASPECT: Record<string, number> = ${JSON.stringify(aspects, null, 2)};

/** The library's own 150px rendition of a cover, where one exists (checked at build). */
export const SHELF_COVER_SMALL: Record<string, string> = ${JSON.stringify(small, null, 2)};
`;
fs.writeFileSync(path.join(root, "src/data/library-plates.ts"), out);
console.log(`plates: ${kept} across ${Object.keys(plates).length} books; covers measured: ${Object.keys(aspects).length}`);
