import type { Metadata } from "next";
import Link from "next/link";
import { Container } from "@/components/Container";
import { SketchPlate } from "@/components/specimens/SketchPlate";
import { SKETCHES, sketchById } from "@/lib/specimens";
import { editorName } from "@/lib/editors";
import { listSpecimenPins, storeConfigured } from "@/lib/store";

/**
 * Specimens — a bench for growing forms from equations, and the gallery of
 * the ones worth keeping.
 *
 * Two halves. The sketches are code (src/lib/specimens): an algorithm and the
 * dials on it. The gallery is data: configurations an editor pinned from the
 * bench, kept in the project's KV store with a thumbnail of what they drew.
 *
 * Draft. `visibility: "draft"` in src/data/projects.ts gates this URL and
 * everything under it, mirrored in public/atlas-nav.js.
 */
export const metadata: Metadata = {
  title: "Specimens. Futures Atlas",
  description: "Organic forms grown from equations: lattice shells, minimal surfaces and reaction–diffusion, each with its dials exposed.",
  robots: { index: false },
};

const label = "font-mono text-[10.5px] uppercase tracking-[0.14em] text-graphite";

function when(ts: number): string {
  return new Date(ts).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
}

export default async function SpecimensPage() {
  const configured = storeConfigured();
  const pins = configured ? await listSpecimenPins() : [];

  return (
    <>
      <section className="py-[clamp(48px,7vw,96px)]">
        <Container>
          <div className="max-w-[60ch]">
            <p className="eyebrow mb-5">Specimens</p>
            <h1 className="text-[clamp(30px,4.4vw,62px)] font-extrabold leading-[1.02] tracking-[-0.022em] text-ink text-balance">
              Forms grown from equations
            </h1>
            <p className="mt-6 text-[15px] leading-[1.8] text-ink-70">
              Every picture here is computed, not drawn and not generated by a model: a few lines of
              geometry or chemistry, rendered on your graphics card as you turn the dials. Each sketch
              says what it computes and where the idea comes from. The ones worth keeping are pinned
              to the gallery below, and every pin reopens on the bench exactly as it was.
            </p>
          </div>
        </Container>
      </section>

      <section className="pb-[clamp(48px,7vw,96px)]">
        <Container>
          <p className={`${label} mb-5`}>Sketches · {SKETCHES.length}</p>
          <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
            {SKETCHES.map((s, i) => (
              <Link key={s.id} href={`/specimens/${s.id}`} prefetch={false} className="fa-card fa-card--link group">
                {/* black in both themes: the specimen's own ground, drawn by the shader */}
                <div className="relative aspect-square overflow-hidden bg-[black]">
                  <SketchPlate sketchId={s.id} />
                </div>
                <div className="flex flex-1 flex-col" style={{ padding: "var(--space-card)" }}>
                  <div className="mb-3 flex items-center justify-between gap-3">
                    <span className="fa-card__meta">{s.family}</span>
                    <span className={label}>{String(i + 1).padStart(2, "0")}</span>
                  </div>
                  <h2 className="fa-card__title">{s.title}</h2>
                  <p className="mt-3 text-[14px] leading-[1.7] text-ink-70">{s.blurb}</p>
                  <span className={`${label} mt-5 self-start border-b border-ink pb-0.5 text-ink`}>Open the bench →</span>
                </div>
              </Link>
            ))}
          </div>
        </Container>
      </section>

      <section className="border-t border-ink/15 py-[clamp(48px,7vw,96px)]">
        <Container>
          <div className="mb-6 flex flex-wrap items-baseline justify-between gap-3">
            <h2 className="text-[clamp(22px,2.4vw,32px)] font-extrabold tracking-[-0.015em] text-ink">The gallery</h2>
            <p className={label}>{configured ? `${pins.length} pinned` : "No store on this deployment"}</p>
          </div>
          {pins.length === 0 ? (
            <p className="max-w-[60ch] text-[14px] leading-[1.8] text-ink-70">
              {configured
                ? "Nothing pinned yet. Open a sketch, find something worth keeping, give it a title and pin it: it lands here for everyone signed in."
                : "Pins live in the project's KV store, which this deployment does not have. Run against an environment with REDIS_URL to see them."}
            </p>
          ) : (
            <div className="grid grid-cols-2 gap-x-4 gap-y-7 sm:grid-cols-3 lg:grid-cols-4">
              {pins.map((p) => {
                const s = sketchById(p.sketch);
                const q = new URLSearchParams(Object.entries(p.values).map(([k, v]) => [k, String(v)])).toString();
                return (
                  <Link key={p.id} href={`/specimens/${p.sketch}${q ? `?${q}` : ""}`} prefetch={false} className="group block">
                    <div className="aspect-square overflow-hidden bg-[black]">
                      {/* eslint-disable-next-line @next/next/no-img-element */}
                      <img src={p.thumb} alt={p.title} loading="lazy" className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" />
                    </div>
                    <p className="mt-2.5 text-[14px] font-semibold leading-[1.35] text-ink">{p.title}</p>
                    {p.note && <p className="mt-1 text-[12.5px] leading-[1.55] text-ink-70">{p.note}</p>}
                    <p className={`${label} mt-1.5`}>
                      {s?.title ?? p.sketch} · {p.by ? editorName(p.by) : "—"} · {when(p.at)}
                    </p>
                  </Link>
                );
              })}
            </div>
          )}
        </Container>
      </section>
    </>
  );
}
