/**
 * atlas-shots.ts — GENERATED by scripts/capture-project-shots.mjs. Do not edit.
 *
 * One entry per Atlas project: its identity, the card art already in the repo,
 * and the screengrabs captured under social-composer/public/shots/<id>/.
 * atlas-source.ts turns an entry into a stocked ComposerSource.
 *
 * Re-run the script whenever a project's look changes.
 */

export type AtlasShot = { file: string; label: string };
export type AtlasProject = {
  id: string; title: string; tagline: string; field: string; path: string;
  cards: string[]; shots: AtlasShot[];
};

export const ATLAS_PROJECTS: AtlasProject[] = [
  {
    "id": "magnifica",
    "title": "Hypothetica Magnifica",
    "tagline": "In May 2026 Pope Leo XIV published the first papal encyclical on AI. Explore the real Magnifica Humanitas, then read sixteen research-grounded, clearly-labeled speculative equivalents — what the Dalai Lama, the Grand Imam of Al-Azhar, the Archbishop of Canterbury and other world faith leaders might write about artificial intelligence.",
    "field": "AI & faith",
    "path": "/magnifica",
    "cards": [
      "/projects/magnifica.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-scroll2-d169.jpg",
        "label": "Home · scroll 2 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "odds-of-surviving-ai",
    "title": "The Odds",
    "tagline": "The people who build and study AI have put odds on the risk. Roll the dice, spin the wheel, draw the card, and gamble on our future.",
    "field": "AI & risk",
    "path": "/theodds",
    "cards": [
      "/projects/odds-of-surviving-ai.jpg",
      "/projects/odds-of-surviving-ai-2.jpg",
      "/projects/odds-of-surviving-ai-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "dario-amodei-d169.jpg",
        "label": "Dario Amodei · 16:9"
      },
      {
        "file": "elon-musk-d169.jpg",
        "label": "Elon Musk · 16:9"
      },
      {
        "file": "max-tegmark-d169.jpg",
        "label": "Max Tegmark · 16:9"
      },
      {
        "file": "stats-d169.jpg",
        "label": "Stats · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "dario-amodei-d32.jpg",
        "label": "Dario Amodei · 3:2"
      },
      {
        "file": "elon-musk-d32.jpg",
        "label": "Elon Musk · 3:2"
      },
      {
        "file": "max-tegmark-d32.jpg",
        "label": "Max Tegmark · 3:2"
      },
      {
        "file": "stats-d32.jpg",
        "label": "Stats · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      },
      {
        "file": "dario-amodei-m916.jpg",
        "label": "Dario Amodei · mobile"
      },
      {
        "file": "elon-musk-m916.jpg",
        "label": "Elon Musk · mobile"
      },
      {
        "file": "max-tegmark-m916.jpg",
        "label": "Max Tegmark · mobile"
      },
      {
        "file": "stats-m916.jpg",
        "label": "Stats · mobile"
      }
    ]
  },
  {
    "id": "signal-reactor",
    "title": "Signal Reactor",
    "tagline": "An organizational foresight instrument: name your organization, get an honest eight-slide briefing on what quantum and advanced AI actually mean for it, deflating the hype, redirecting to the real signal. AI-generated and labeled as such; built to structure a stakeholder conversation, not to make the decision.",
    "field": "AI & risk",
    "path": "/signal-reactor",
    "cards": [
      "/projects/signal-reactor-2.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "quantum-spark",
    "title": "Quantum Spark",
    "tagline": "Signal Reactor's energized companion: type your industry and get five bold, grounded glimpses of how quantum computing and next-wave AI will transform it, the kind of insight that makes a room lean forward. Grounded hype with an honest label: provocations to spark conversation, not forecasts.",
    "field": "AI & risk",
    "path": "/quantum-spark",
    "cards": [
      "/projects/quantum-spark-2.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "manipulate-ai-index",
    "title": "The Counterfactual Index",
    "tagline": "The 2026 Stanford AI Index, rebuilt from the report's own published CSVs so the numbers are theirs rather than an approximation of theirs, then redrawn under decisions nobody took. Say what you would do about AI and when: sixteen figures move, or say plainly that they don't and name the lever that was missing. An intervention never invents a data point. It emits a typed, dated transform over the real series, carrying a stated reason and a confidence you can argue with.",
    "field": "Manipulate the data",
    "path": "/manipulate-the-data",
    "cards": [
      "/projects/manipulate-ai-index.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "manipulate-quantum",
    "title": "Counterfactual Quantum",
    "tagline": "Quantum has no AI Index, so this board is assembled: publication counts pulled from OpenAlex and queried by topic, next to the two endpoints Quantum Delta NL's own report actually publishes. The Dutch programme runs out of Growth Fund money in 2028 and that report ends by asking what happens next, so four of the six interventions are versions of that question. Delft's output inflected in 2017, three years before the programme existed.",
    "field": "Manipulate the data",
    "path": "/manipulate-the-data/quantum",
    "cards": [
      "/projects/manipulate-quantum.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "manipulate-ai-gigawatts",
    "title": "AI Gigawatts",
    "tagline": "Global AI data centre power capacity as a rising field of light, marking the countries it passes on the way up: New Zealand, the Netherlands, New York State at peak. Pick a decision and the counterfactual is cut from the glow as a solid shape, so the gap is the subject rather than two lines to compare.",
    "field": "Manipulate the data",
    "path": "/manipulate-the-data/ai-gigawatts",
    "cards": [
      "/projects/manipulate-ai-gigawatts.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "hyperscale",
    "title": "Hyperscale",
    "tagline": "A 3D management sim about the physical reality of the AI buildout, a compute campus in a river valley with a town next door. Mix grid, solar, wind, gas and batteries; keep GPU halls cool through heat waves and dust storms; watch the aquifer, the smog and civic sentiment as you grow toward a gigawatt. Full day–night cycle, seeded weather and markets, procedural audio.",
    "field": "Simulation",
    "path": "/hyperscale",
    "cards": [
      "/projects/hyperscale-2.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "hollow-villages",
    "title": "Village Oracle",
    "tagline": "An AI oracle forecasting how depopulating rural villages could be revived, people write it letters; it answers with grounded, cited plans and a picture of the place in 2050.",
    "field": "Rural futures",
    "path": "/village-oracle",
    "cards": [
      "/projects/hollow-villages.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "oracle-d169.jpg",
        "label": "Oracle · 16:9"
      },
      {
        "file": "research-d169.jpg",
        "label": "Research · 16:9"
      },
      {
        "file": "research-scroll1-d169.jpg",
        "label": "Research · scroll 1 · 16:9"
      },
      {
        "file": "research-scroll2-d169.jpg",
        "label": "Research · scroll 2 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "oracle-d32.jpg",
        "label": "Oracle · 3:2"
      },
      {
        "file": "research-d32.jpg",
        "label": "Research · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      },
      {
        "file": "oracle-m916.jpg",
        "label": "Oracle · mobile"
      },
      {
        "file": "research-m916.jpg",
        "label": "Research · mobile"
      }
    ]
  },
  {
    "id": "generatives",
    "title": "Generatives",
    "tagline": "A generative-visual lab, an array of animated, embeddable treatments (flow fields, noise, interference) for the project's visual language. Each one tunable, resizable to any banner, and copy-paste embeddable.",
    "field": "Generative visuals",
    "path": "/generatives",
    "cards": [
      "/projects/generatives-4.jpg",
      "/projects/generatives-2.jpg",
      "/projects/generatives-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "swipe-the-future",
    "title": "Swipe the Future",
    "tagline": "A calibration game with one question: has this already happened, or not yet? Forty sourced claims, half of them older than you would guess. Swipe, then see which futures everyone buys early and which ones arrived while nobody was looking.",
    "field": "Calibration",
    "path": "/swipe-the-future",
    "cards": [
      "/projects/swipe-the-future.jpg",
      "/projects/swipe-the-future-2.jpg",
      "/projects/swipe-the-future-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "stats-d169.jpg",
        "label": "Stats · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "stats-d32.jpg",
        "label": "Stats · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      },
      {
        "file": "stats-m916.jpg",
        "label": "Stats · mobile"
      }
    ]
  },
  {
    "id": "swipe-v1",
    "title": "Swipe the Future v1",
    "tagline": "The first version, frozen: pick a job, swipe Believe or Doubt on six claims, get a calibration score. Kept playable beside the current game, which asks whether a thing has already happened rather than whether it is true.",
    "field": "Calibration",
    "path": "/swipe-v1",
    "cards": [
      "/projects/swipe-v1.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "trajectories",
    "title": "Trajectories",
    "tagline": "A real-time sphere of luminous filaments: thousands of strands reach from a boiling core to the shell, bending through noise that grows with radius, while pulses of brightness flow outward and ripples bloom at the surface. A non-commercial reimplementation (WebGL) of Jeongho Park's “Collective Trajectories” (CC BY-NC 4.0).",
    "field": "Generative visuals",
    "path": "/trajectories",
    "cards": [
      "/projects/trajectories.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "quantum-lag",
    "title": "Quantum Lag",
    "tagline": "Place twenty claims about quantum technology on a timeline, then find out where they actually sit. It measures a specific error: people put finished work in the future and unfinished work in the past.",
    "field": "AI & risk",
    "path": "/quantum-lag",
    "cards": [
      "/projects/quantum-lag.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "study-d169.jpg",
        "label": "Study · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "study-d32.jpg",
        "label": "Study · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      },
      {
        "file": "study-m916.jpg",
        "label": "Study · mobile"
      }
    ]
  },
  {
    "id": "quantum-dominance",
    "title": "Quantum Dominance",
    "tagline": "Speculative satire: one official 'quantum dominance' post, two lenses. Pick The Dystopia or The Backfire and explore randomized futures, each anchored to something on the record, ready to push into the composer.",
    "field": "AI & risk",
    "path": "/quantum-dominance",
    "cards": [
      "/projects/quantum-dominance.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "woodchipper",
    "title": "Woodchipper Futures",
    "tagline": "An interactive futures engine on the 2025 USAID cuts: take the January-2025 chair, abolish, freeze, audit or reform, and watch a fact-checked, source-cited constellation of outcomes branch out. Every figure links to its study.",
    "field": "AI & risk",
    "path": "/woodchipper",
    "cards": [
      "/projects/woodchipper.jpg",
      "/projects/woodchipper-2.jpg",
      "/projects/woodchipper-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-scroll2-d169.jpg",
        "label": "Home · scroll 2 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "actually-hard-questions",
    "title": "Actually Hard Questions",
    "tagline": "A parody of Anthropic's own homepage banner, hiding a workshop tool: hang a room's hardest AI questions on Anthropic's five real headings, next to what Anthropic has actually published there.",
    "field": "Public engagement",
    "path": "/actually-hard-questions",
    "cards": [
      "/projects/actually-hard-questions.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "underground-intelligence",
    "title": "Underground Intelligence",
    "tagline": "An investigation into the unseen systems beneath everyday life, built on a traceable evidence base where every claim links back to its source.",
    "field": "Systems & evidence",
    "path": "/underground-intelligence",
    "cards": [
      "/projects/underground-intelligence.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "story-d169.jpg",
        "label": "Story · 16:9"
      },
      {
        "file": "dashboard-d169.jpg",
        "label": "Dashboard · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "story-d32.jpg",
        "label": "Story · 3:2"
      },
      {
        "file": "dashboard-d32.jpg",
        "label": "Dashboard · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      },
      {
        "file": "story-m916.jpg",
        "label": "Story · mobile"
      },
      {
        "file": "dashboard-m916.jpg",
        "label": "Dashboard · mobile"
      }
    ]
  },
  {
    "id": "quantum-sandbox",
    "title": "Quantum Sandbox",
    "tagline": "A prototyping dashboard for quantum-computing generative systems, every amplitude drawn as colour, with magnitude as density and phase as hue.",
    "field": "Quantum & computation",
    "path": "/quantum-sandbox",
    "cards": [
      "/projects/quantum-sandbox.jpg",
      "/projects/quantum-sandbox-2.jpg",
      "/projects/quantum-sandbox-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "literal-frequency",
    "title": "Literal Frequency",
    "tagline": "Word-frequency visualisations built live from the Source Library, the open-access archive of digitised, translated books. Loads a book over the API and reads its vocabulary as a cloud, a word nebula, a bubble field, or bars, each view linking back to its source.",
    "field": "Data visualisation",
    "path": "/literal-frequency",
    "cards": [
      "/projects/literal-frequency.jpg",
      "/projects/literal-frequency-2.jpg",
      "/projects/literal-frequency-3.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-scroll2-d169.jpg",
        "label": "Home · scroll 2 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  },
  {
    "id": "social-composer",
    "title": "Social Composer",
    "tagline": "A standalone social-post composer, post types, layouts, motion, and PNG / GIF / video export, with a URL “transmutate” importer that pulls the reusable pieces out of any article.",
    "field": "Creative tools",
    "path": "/social-composer",
    "cards": [
      "/projects/social-composer.jpg"
    ],
    "shots": [
      {
        "file": "home-d169.jpg",
        "label": "Home · 16:9"
      },
      {
        "file": "home-scroll1-d169.jpg",
        "label": "Home · scroll 1 · 16:9"
      },
      {
        "file": "home-d32.jpg",
        "label": "Home · 3:2"
      },
      {
        "file": "home-m916.jpg",
        "label": "Home · mobile"
      }
    ]
  }
];
