/**
 * GENERATED by scripts/ancestors/build-plates.mjs. Do not edit by hand.
 *
 * SHELF_PLATES: illustrations the Source Library has extracted from each book's
 * scans, best first. Captions are the library's own descriptions. Books the
 * library has extracted nothing from are simply absent.
 * SHELF_COVER_ASPECT: width / height of each cover scan, so a tile can show the
 * page whole instead of cropping it to a common shape.
 * SHELF_COVER_SMALL: a light rendition of the cover for the field of tiles.
 */

export interface ShelfPlate {
  src: string;
  thumb: string;
  /** width / height of the extracted image */
  aspect: number;
  /** page of the scan it was taken from */
  page: number;
  kind: string;
  caption: string;
}

export const SHELF_PLATES: Record<string, ShelfPlate[]> = {
  "69dbcac31040d1d5e20ae6df": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6e5-0.jpg?v=1781709834668",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6e5-0-thumb.jpg?v=1781709834668",
      "aspect": 0.779,
      "page": 6,
      "kind": "woodcut",
      "caption": "Complex cosmological and astrological woodcut featuring a central zodiac wheel surrounded by planetary deities in chariots and various allegorical figures."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6e6-0.jpg?v=1781709834649",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6e6-0-thumb.jpg?v=1781709834649",
      "aspect": 1.055,
      "page": 7,
      "kind": "woodcut",
      "caption": "Woodcut of a scholar or prophet observing celestial signs"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae72e-0.jpg?v=1781709837835",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae72e-0-thumb.jpg?v=1781709837835",
      "aspect": 1.286,
      "page": 79,
      "kind": "woodcut",
      "caption": "A woodcut depicting a central prophetic figure addressing a group of high-ranking religious and secular authorities, including a Pope and an Emperor."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6f7-0.jpg?v=1781709835448",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6f7-0-thumb.jpg?v=1781709835448",
      "aspect": 1.303,
      "page": 24,
      "kind": "woodcut",
      "caption": "Christ (Salvator) addressing the King of the Romans and his armed retinue."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6f1-0.jpg?v=1781709834673",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6f1-0-thumb.jpg?v=1781709834673",
      "aspect": 1.337,
      "page": 18,
      "kind": "woodcut",
      "caption": "Christ in Majesty as Salvator Mundi, flanked by the Pope and Emperor."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6fd-0.jpg?v=1781709835812",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbcac31040d1d5e20ae6df/69dbcac31040d1d5e20ae6fd-0-thumb.jpg?v=1781709835812",
      "aspect": 1.34,
      "page": 30,
      "kind": "woodcut",
      "caption": "A woodcut depicting the Massacre of the Innocents with three armed men killing infants in a landscape."
    }
  ],
  "69dbc7d91040d1d5e2094b55": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b6f-0.jpg?v=1781709613238",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b6f-0-thumb.jpg?v=1781709613238",
      "aspect": 0.936,
      "page": 26,
      "kind": "diagram",
      "caption": "Astrological square diagram of the twelve houses of heaven"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b60-0.jpg?v=1780588625235",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b60-0-thumb.jpg?v=1780588625235",
      "aspect": 0.936,
      "page": 11,
      "kind": "diagram",
      "caption": "Astrological diagram showing the aspects between Saturn and the Moon"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b57-0.jpg?v=1781709613356",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b57-0-thumb.jpg?v=1781709613356",
      "aspect": 0.652,
      "page": 2,
      "kind": "engraving",
      "caption": "Heraldic bookplate of the Bibliotheca Regia Monacensis featuring a coat of arms with lion supporters and a royal crown."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5b-0.jpg?v=1780589226811",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5b-0-thumb.jpg?v=1780589226811",
      "aspect": 0.988,
      "page": 6,
      "kind": "diagram",
      "caption": "Astrological diagram showing the aspects between Saturn and Jupiter."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5c-0.jpg?v=1780589226887",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5c-0-thumb.jpg?v=1780589226887",
      "aspect": 0.981,
      "page": 7,
      "kind": "diagram",
      "caption": "Astrological diagram showing the aspects between Saturn, Jupiter, and Mars."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5d-0.jpg?v=1780589226874",
      "thumb": "https://images.sourcelibrary.org/gallery/69dbc7d91040d1d5e2094b55/69dbc7d91040d1d5e2094b5d-0-thumb.jpg?v=1780589226874",
      "aspect": 0.932,
      "page": 8,
      "kind": "diagram",
      "caption": "Astrological diagram showing aspects between Saturn and the Sun"
    }
  ],
  "695592c17bd6d2cd1d61afec": [
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b014-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b014-0-thumb.jpg",
      "aspect": 1.133,
      "page": 40,
      "kind": "diagram",
      "caption": "A circular diagram known as a Lullian wheel, consisting of three concentric rings divided into segments labeled with letters B through K. Some segments are hand-colored in yellow, green, and red."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b010-0.jpg?v=1773407540131",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b010-0-thumb.jpg?v=1773407540131",
      "aspect": 0.787,
      "page": 36,
      "kind": "diagram",
      "caption": "A complex circular philosophical diagram titled 'SECUNDA FIGURA' featuring concentric rings, an eight-pointed star, and a central green triangle with the letter 'T'."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b013-0.jpg?v=1771876759555",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b013-0-thumb.jpg?v=1771876759555",
      "aspect": 1.049,
      "page": 39,
      "kind": "diagram",
      "caption": "A large combinatorial grid containing pairs of capital letters from B to K."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b0bc-1.jpg?v=1771876772415",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b0bc-1-thumb.jpg?v=1771876772415",
      "aspect": 1.021,
      "page": 208,
      "kind": "diagram",
      "caption": "Large geometric diagram showing a circle inscribed within a square, which is itself enclosed by a larger square."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b0c6-0.jpg?v=1771876770884",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b0c6-0-thumb.jpg?v=1771876770884",
      "aspect": 0.991,
      "page": 218,
      "kind": "diagram",
      "caption": "Geometric diagram for navigation showing a triangle within a circle divided into four numbered sections."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b104-0.jpg?v=1773156610352",
      "thumb": "https://images.sourcelibrary.org/gallery/695592c17bd6d2cd1d61afec/695592c17bd6d2cd1d61b104-0-thumb.jpg?v=1773156610352",
      "aspect": 0.743,
      "page": 280,
      "kind": "woodcut",
      "caption": "Woodcut of Saints Peter and Paul holding the Veil of Veronica with the face of Christ."
    }
  ],
  "69bfcf9c3047130b1c3bfa3e": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa48-1.jpg?v=1781697176438",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa48-1-thumb.jpg?v=1781697176438",
      "aspect": 1.472,
      "page": 10,
      "kind": "diagram",
      "caption": "A schematic view of Constantinople featuring city walls, domed buildings, and a tomb with a skeleton."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa40-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa40-0-thumb.jpg",
      "aspect": 0.585,
      "page": 2,
      "kind": "diagram",
      "caption": "A composite illustration featuring a central ox standing above a map of Cyprus, flanked by three human heads, one wearing a turban."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa41-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa41-0-thumb.jpg",
      "aspect": 0.69,
      "page": 3,
      "kind": "emblem",
      "caption": "A fortified city with a central chalice containing a severed head, positioned above a fleet of ships at sea."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa44-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa44-0-thumb.jpg",
      "aspect": 1.111,
      "page": 6,
      "kind": "portrait",
      "caption": "A seated scholar with a halo writing on a tablet next to an open sarcophagus containing a skeleton."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa43-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa43-0-thumb.jpg",
      "aspect": 0.633,
      "page": 5,
      "kind": "portrait",
      "caption": "A hand-colored illustration of a mounted knight in armor, depicted as a statue atop a marble pedestal."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa3f-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69bfcf9c3047130b1c3bfa3e/69bfcf9c3047130b1c3bfa3f-0-thumb.jpg",
      "aspect": 0.895,
      "page": 1,
      "kind": "emblem",
      "caption": "An allegorical illustration of an eagle holding a cross in its beak, perched on the back of a unicorn."
    }
  ],
  "69b21cc3429e087c6f86586b": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b21cc3429e087c6f86586b/69b21cc3429e087c6f86586c-0.jpg?v=1790307889217",
      "thumb": "https://images.sourcelibrary.org/gallery/69b21cc3429e087c6f86586b/69b21cc3429e087c6f86586c-0-thumb.jpg?v=1790307889217",
      "aspect": 0.671,
      "page": 1,
      "kind": "exlibris",
      "caption": "Blind-stamped monogram on a leather book binding"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b21cc3429e087c6f86586b/69b21cc3429e087c6f865870-0.jpg?v=1790307888548",
      "thumb": "https://images.sourcelibrary.org/gallery/69b21cc3429e087c6f86586b/69b21cc3429e087c6f865870-0-thumb.jpg?v=1790307888548",
      "aspect": 2.932,
      "page": 5,
      "kind": "exlibris",
      "caption": "Fore-edge view of a closed 16th-century book with red-stained paper edges and gold-tooled leather binding."
    }
  ],
  "69b65cf7b3f4fc0441515dbf": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515dff-0.jpg?v=1781709541945",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515dff-0-thumb.jpg?v=1781709541945",
      "aspect": 0.676,
      "page": 64,
      "kind": "engraving",
      "caption": "A complex multi-level mechanical system featuring a central vertical screw, large drive wheels, and workers carrying sacks."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e27-0.jpg?v=1781709542409",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e27-0-thumb.jpg?v=1781709542409",
      "aspect": 0.685,
      "page": 104,
      "kind": "engraving",
      "caption": "A complex mechanical well system shown in both surface view and underground cross-section."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e13-0.jpg?v=1781709542384",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e13-0-thumb.jpg?v=1781709542384",
      "aspect": 0.757,
      "page": 84,
      "kind": "engraving",
      "caption": "A detailed technical engraving of a large wooden crane or lifting machine, featuring a central pillar, a pivoting arm with a counterweight, and a screw mechanism. Two men are shown operating the device near a shoreline."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515deb-0.jpg?v=1781709541076",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515deb-0-thumb.jpg?v=1781709541076",
      "aspect": 0.613,
      "page": 44,
      "kind": "engraving",
      "caption": "A complex and highly detailed engraving of an ornate carriage or chariot pulled by a team of horses, featuring mechanical components and allegorical figures."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e0f-0.jpg?v=1780586923631",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515e0f-0-thumb.jpg?v=1780586923631",
      "aspect": 0.768,
      "page": 80,
      "kind": "engraving",
      "caption": "A detailed engraving showing a complex hoisting machine used in the construction of a stone wall, featuring a large treadmill wheel and several workers."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515ddb-0.jpg?v=1781709541092",
      "thumb": "https://images.sourcelibrary.org/gallery/69b65cf7b3f4fc0441515dbf/69b65cf7b3f4fc0441515ddb-0-thumb.jpg?v=1781709541092",
      "aspect": 0.77,
      "page": 28,
      "kind": "engraving",
      "caption": "Technical engraving of a screw-cutting lathe, showing a detailed screw above and the full machine with an operator below."
    }
  ],
  "695aa9a4be4023bd34bd6b7d": [
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6ba6-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6ba6-0-thumb.jpg",
      "aspect": 0.427,
      "page": 41,
      "kind": "diagram",
      "caption": "Engraving of a mobile self-moving machine (automaton) with an architectural base and a figurative temple on top."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bb7-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bb7-0-thumb.jpg",
      "aspect": 0.652,
      "page": 58,
      "kind": "diagram",
      "caption": "Technical diagram of an automated temple mechanism featuring pulleys, weights, and siphons."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bbb-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bbb-0-thumb.jpg",
      "aspect": 0.568,
      "page": 62,
      "kind": "diagram",
      "caption": "Technical diagram of an automaton mechanism featuring a rotating ring with figures and a pulley-driven axle system, as described in Hero of Alexandria's work."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bc9-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bc9-0-thumb.jpg",
      "aspect": 0.698,
      "page": 76,
      "kind": "diagram",
      "caption": "Technical diagram of a mechanism for a 'stable machine', showing a system of pulleys, ropes, and a counterweight to operate doors or panels."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bab-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bab-0-thumb.jpg",
      "aspect": 0.755,
      "page": 46,
      "kind": "diagram",
      "caption": "Technical diagram of a sand-driven automaton mechanism with pulleys and weights."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bc3-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/695aa9a4be4023bd34bd6b7d/695aa9a4be4023bd34bd6bc3-0-thumb.jpg",
      "aspect": 0.398,
      "page": 70,
      "kind": "diagram",
      "caption": "A detailed technical illustration of a stationary automaton, designed as a classical architectural structure with columns, a pediment, and open doors revealing an internal panel labeled 'TAVOLA'."
    }
  ],
  "69a5d8cda63a00aaae8aaae5": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaea-0.jpg?v=1789875087636",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaea-0-thumb.jpg?v=1789875087636",
      "aspect": 0.72,
      "page": 5,
      "kind": "engraving",
      "caption": "An allegorical engraving depicting the first encounter between Amerigo Vespucci and the personification of America. Vespucci stands on the left with a crucifix staff and astrolabe, while a nude indigenous woman representing America reclines in a hammock. The background features exotic animals, ships, and a scene of cannibalism."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaee-0.jpg?v=1789875091515",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaee-0-thumb.jpg?v=1789875091515",
      "aspect": 0.735,
      "page": 9,
      "kind": "engraving",
      "caption": "A detailed 16th-century engraving titled 'PVLVIS PYRIVS' (Gunpowder) from the 'Nova Reperta' series, depicting a cannon foundry. In the foreground, craftsmen finish cannon barrels with hammers and chisels. In the center, molten metal flows from a brick furnace into a mold under the supervision of a master founder. An inset image above the furnace shows a laboratory with chemical apparatus. The background features a water wheel and a distant scene of a city under siege by artillery."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab02-0.jpg?v=1789875095150",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab02-0-thumb.jpg?v=1789875095150",
      "aspect": 0.742,
      "page": 29,
      "kind": "engraving",
      "caption": "An engraving titled 'CONSPICILLA' (Spectacles) from the Nova Reperta series, showing a spectacle-maker's shop and customers testing various eyeglasses in an urban setting."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab04-0.jpg?v=1789875096088",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab04-0-thumb.jpg?v=1789875096088",
      "aspect": 0.72,
      "page": 31,
      "kind": "engraving",
      "caption": "A detailed engraving from the 'Nova Reperta' series showing a large sailing vessel navigating a rough sea, featuring a man at a table using a magnetic compass to determine longitude."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab06-0.jpg?v=1789875096353",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aab06-0-thumb.jpg?v=1789875096353",
      "aspect": 0.72,
      "page": 33,
      "kind": "engraving",
      "caption": "A detailed 16th-century copperplate engraving titled 'POLITVRA ARMORVM' (Polishing of Armor) from the 'Nova Reperta' series. The scene depicts a bustling armor-polishing workshop where craftsmen use large, water-powered grinding wheels to finish various pieces of plate armor. In the foreground, a master craftsman inspects a breastplate while an apprentice works beside him; to the left, a boy carries a basket of armor components. The workshop is filled with helmets, gauntlets, and cuirasses, showcasing the industrial scale of early modern arms production."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaec-0.jpg?v=1789875091600",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5d8cda63a00aaae8aaae5/69a5d8cda63a00aaae8aaaec-0-thumb.jpg?v=1789875091600",
      "aspect": 0.72,
      "page": 7,
      "kind": "engraving",
      "caption": "A detailed late 16th-century engraving titled 'LAPIS POLARIS, MAGNES' depicting a scholar in his study surrounded by navigational and scientific instruments, including a floating lodestone in a basin, an armillary sphere, a globe, and a model ship."
    }
  ],
  "69b6660eb3f4fc0441558978": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589e6-0.jpg?v=1781731881616",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589e6-0-thumb.jpg?v=1781731881616",
      "aspect": 0.728,
      "page": 110,
      "kind": "diagram",
      "caption": "A complex geometric diagram within a rectangular frame, featuring a dense web of intersecting lines connecting points labeled with letters A through M, with a central point N."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a35-0.jpg?v=1781731882110",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a35-0-thumb.jpg?v=1781731882110",
      "aspect": 0.706,
      "page": 189,
      "kind": "diagram",
      "caption": "A complex geometric mnemonic diagram titled 'ARCHETYPVS' featuring a rectangular frame with lettered points connected by a dense web of lines."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a30-0.jpg?v=1781731882137",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a30-0-thumb.jpg?v=1781731882137",
      "aspect": 0.846,
      "page": 184,
      "kind": "diagram",
      "caption": "Mnemonic diagram featuring a lettered grid and a diagonal line, titled 'Vexillum'."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589c6-0.jpg?v=1781731881583",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589c6-0-thumb.jpg?v=1781731881583",
      "aspect": 1.108,
      "page": 78,
      "kind": "diagram",
      "caption": "Mnemonic diagram 'Cubilium Minorum Figura' with concentric circles, a square, and inscribed triangles containing letters."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589a1-0.jpg?v=1781731881691",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc04415589a1-0-thumb.jpg?v=1781731881691",
      "aspect": 1.012,
      "page": 41,
      "kind": "diagram",
      "caption": "A complex mnemonic diagram featuring a circle enclosing a square, which in turn contains a central circle and four diamond shapes at the cardinal points, all populated with letters."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a41-0.jpg?v=1781731882245",
      "thumb": "https://images.sourcelibrary.org/gallery/69b6660eb3f4fc0441558978/69b6660eb3f4fc0441558a41-0-thumb.jpg?v=1781731882245",
      "aspect": 0.887,
      "page": 201,
      "kind": "diagram",
      "caption": "A mnemonic or philosophical diagram consisting of a pyramid of letters (A-F) atop a vertical column of letters."
    }
  ],
  "6956890dbe7c607c5f03c7d9": [
    {
      "src": "https://images.sourcelibrary.org/gallery/6956890dbe7c607c5f03c7d9/69569d361479a63c11091612-1.jpg?v=1771876816142",
      "thumb": "https://images.sourcelibrary.org/gallery/6956890dbe7c607c5f03c7d9/69569d361479a63c11091612-1-thumb.jpg?v=1771876816142",
      "aspect": 1.056,
      "page": 10,
      "kind": "engraving",
      "caption": "Sketch-like illustration of a man in profile, standing and holding a long object, possibly a fishing rod."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6956890dbe7c607c5f03c7d9/69569d361479a63c11091609-0.jpg?v=1781661276939",
      "thumb": "https://images.sourcelibrary.org/gallery/6956890dbe7c607c5f03c7d9/69569d361479a63c11091609-0-thumb.jpg?v=1781661276939",
      "aspect": 1.774,
      "page": 1,
      "kind": "frontispiece",
      "caption": "A landscape painting of a classical city at sunrise"
    }
  ],
  "69a5b99dd76b98f272fcec6d": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fced02-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fced02-0-thumb.jpg",
      "aspect": 0.753,
      "page": 149,
      "kind": "engraving",
      "caption": "Detailed engraving of Orpheus charming animals with music in a rocky grotto setting."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecc0-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecc0-0-thumb.jpg",
      "aspect": 0.691,
      "page": 83,
      "kind": "engraving",
      "caption": "A large-scale engraving illustrating a hydraulic grotto. The upper portion shows Orpheus playing a flute to animals, while the lower portion details the internal water-wheel and gear mechanism."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecfc-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecfc-0-thumb.jpg",
      "aspect": 0.937,
      "page": 143,
      "kind": "engraving",
      "caption": "Engraving of a colossal river god seated on a rocky island within a formal garden pool."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcece2-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcece2-0-thumb.jpg",
      "aspect": 0.719,
      "page": 117,
      "kind": "engraving",
      "caption": "Engraving of an elaborate grotto with mythological figures and hydraulic fountains."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecb6-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecb6-0-thumb.jpg",
      "aspect": 0.705,
      "page": 73,
      "kind": "engraving",
      "caption": "A scene depicting men using a large hydraulic pump to extinguish a fire in a building."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecfa-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5b99dd76b98f272fcec6d/69a5b99dd76b98f272fcecfa-0-thumb.jpg",
      "aspect": 1.051,
      "page": 141,
      "kind": "engraving",
      "caption": "An elaborate engraving of a fountain representing Mount Parnassus, featuring Apollo, the Muses, and Pegasus."
    }
  ],
  "695294dbb184004c526a272b": [
    {
      "src": "https://images.sourcelibrary.org/gallery/695294dbb184004c526a272b/695906b795a91542b28beae9-0.jpg?v=1771877004153",
      "thumb": "https://images.sourcelibrary.org/gallery/695294dbb184004c526a272b/695906b795a91542b28beae9-0-thumb.jpg?v=1771877004153",
      "aspect": 0.925,
      "page": 2,
      "kind": "engraving",
      "caption": "A decorative emblem featuring a crown atop an intertwined monogram, enclosed in a rococo-style cartouche with the date 1913."
    }
  ],
  "69905cf8aaa7f10ed4cfd202": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69905cf8aaa7f10ed4cfd202/69905cf8aaa7f10ed4cfd217-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69905cf8aaa7f10ed4cfd202/69905cf8aaa7f10ed4cfd217-0-thumb.jpg",
      "aspect": 0.687,
      "page": 21,
      "kind": "engraving",
      "caption": "Domingo Gonsales being lifted into the air by a team of gansas (wild swans) using a complex harness and frame."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69905cf8aaa7f10ed4cfd202/69905cf8aaa7f10ed4cfd224-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69905cf8aaa7f10ed4cfd202/69905cf8aaa7f10ed4cfd224-0-thumb.jpg",
      "aspect": 0.524,
      "page": 34,
      "kind": "map",
      "caption": "Topographical view of the island of Saint Helena showing its mountainous terrain and coastline."
    }
  ],
  "69b51ea29a81ef7feb3d84e3": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d856e-0.jpg?v=1781731262138",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d856e-0-thumb.jpg?v=1781731262138",
      "aspect": 1.152,
      "page": 139,
      "kind": "diagram",
      "caption": "The Lullian 'Figura T' diagram, a complex circular schema used for combinatorial logic."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8567-0.jpg?v=1781731262040",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8567-0-thumb.jpg?v=1781731262040",
      "aspect": 1.152,
      "page": 132,
      "kind": "diagram",
      "caption": "A Lullian combinatorial wheel or diagram featuring concentric circles divided into segments."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d857a-0.jpg?v=1781731262120",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d857a-0-thumb.jpg?v=1781731262120",
      "aspect": 1.216,
      "page": 151,
      "kind": "diagram",
      "caption": "A circular Lullian diagram divided into segments containing Latin terms and letters."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8560-0.jpg?v=1781731262145",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8560-0-thumb.jpg?v=1781731262145",
      "aspect": 1.113,
      "page": 125,
      "kind": "diagram",
      "caption": "Lullian combinatorial diagram (Figure S) representing the nine universal subjects."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d852f-0.jpg?v=1781731261704",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d852f-0-thumb.jpg?v=1781731261704",
      "aspect": 0.942,
      "page": 76,
      "kind": "diagram",
      "caption": "A geometric logical diagram consisting of two overlapping squares forming a star-like pattern with vertices labeled A through H."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8521-0.jpg?v=1781731261659",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ea29a81ef7feb3d84e3/69b51ea29a81ef7feb3d8521-0-thumb.jpg?v=1781731261659",
      "aspect": 1.14,
      "page": 62,
      "kind": "diagram",
      "caption": "A circular Lullian diagram divided into segments containing letters of the alphabet (B through K)."
    }
  ],
  "69b1c67aedda7fb64e1a1201": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12b8-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12b8-0-thumb.jpg",
      "aspect": 0.645,
      "page": 183,
      "kind": "diagram",
      "caption": "A detailed celestial diagram from an astronomical treatise, showing stars, constellations such as Bootes and Corona Borealis, and geometric lines for measurement against a dark sky background."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a125d-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a125d-0-thumb.jpg",
      "aspect": 0.503,
      "page": 92,
      "kind": "diagram",
      "caption": "Woodcut diagram showing three phases of a comet's appearance in 1618."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a1241-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a1241-0-thumb.jpg",
      "aspect": 0.71,
      "page": 64,
      "kind": "diagram",
      "caption": "Astronomical diagram showing planetary orbits and celestial paths on a dark background."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a1234-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a1234-0-thumb.jpg",
      "aspect": 0.815,
      "page": 51,
      "kind": "diagram",
      "caption": "Astronomical diagram showing cometary orbits around the sun"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12ab-1.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12ab-1-thumb.jpg",
      "aspect": 1.832,
      "page": 170,
      "kind": "diagram",
      "caption": "Astronomical diagram of a star field titled 'NEBVLOSA EDUCTIONIS CAVDÆ SYRII'."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12ab-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b1c67aedda7fb64e1a1201/69b1c67aedda7fb64e1a12ab-0-thumb.jpg",
      "aspect": 0.583,
      "page": 170,
      "kind": "diagram",
      "caption": "Astronomical diagram of a star field titled 'LVMINOSA CAVDÆ SYRI'."
    }
  ],
  "69a5f6cd1cf742c3604142ea": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041441c-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041441c-0-thumb.jpg",
      "aspect": 0.878,
      "page": 306,
      "kind": "engraving",
      "caption": "Engraving of a hydraulic or pneumatic mechanism featuring two robed figures pouring liquid onto an altar."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c360414422-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c360414422-0-thumb.jpg",
      "aspect": 0.83,
      "page": 312,
      "kind": "engraving",
      "caption": "Technical diagrams of hydraulic and pneumatic machines, including a heat-driven automaton and a water-based apparatus."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c360414512-1.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c360414512-1-thumb.jpg",
      "aspect": 1.397,
      "page": 552,
      "kind": "engraving",
      "caption": "Engraving of a pneumatic device featuring a personified wind head blowing air into a mechanical chamber."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041447a-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041447a-0-thumb.jpg",
      "aspect": 0.682,
      "page": 400,
      "kind": "engraving",
      "caption": "Engraved plate 'Iconismus XXVII' featuring three ornate hydraulic vessels and two mechanical diagrams of a balance scale."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041444c-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c36041444c-0-thumb.jpg",
      "aspect": 1.004,
      "page": 354,
      "kind": "engraving",
      "caption": "Technical diagrams of two hydraulic apparatuses, labeled Figure I and Figure II, featuring reservoirs, basins, and grotesque mask spouts."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c3604143dc-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6cd1cf742c3604142ea/69a5f6cd1cf742c3604143dc-0-thumb.jpg",
      "aspect": 0.699,
      "page": 242,
      "kind": "engraving",
      "caption": "Technical diagrams of hydraulic and pneumatic machines, featuring a tiered fountain and a wind-powered pump."
    }
  ],
  "69905d0eaaa7f10ed4cfd7bd": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69905d0eaaa7f10ed4cfd7bd/69905d0faaa7f10ed4cfd7c9-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69905d0eaaa7f10ed4cfd7bd/69905d0faaa7f10ed4cfd7c9-0-thumb.jpg",
      "aspect": 0.797,
      "page": 11,
      "kind": "frontispiece",
      "caption": "Frontispiece for 'L'Agripine' featuring a coat of arms and a dramatic scene with two figures in classical attire."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69905d0eaaa7f10ed4cfd7bd/69905d0faaa7f10ed4cfd7c2-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69905d0eaaa7f10ed4cfd7bd/69905d0faaa7f10ed4cfd7c2-0-thumb.jpg",
      "aspect": 0.624,
      "page": 4,
      "kind": "frontispiece",
      "caption": "A complex frontispiece illustration featuring allegorical figures, architectural elements, and celestial motifs, characteristic of 17th-century French literary works."
    }
  ],
  "69b185aac4be2cdd0edc3e24": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b185aac4be2cdd0edc3e24/69b185aac4be2cdd0edc3e6d-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b185aac4be2cdd0edc3e24/69b185aac4be2cdd0edc3e6d-0-thumb.jpg",
      "aspect": 0.423,
      "page": 73,
      "kind": "diagram",
      "caption": "Geometric diagram illustrating optical principles with a circle and converging lines."
    }
  ],
  "69b51ed847b06ecd58197576": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69b51ed847b06ecd58197576/69b51ed847b06ecd5819757b-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/69b51ed847b06ecd58197576/69b51ed847b06ecd5819757b-0-thumb.jpg",
      "aspect": 0.705,
      "page": 5,
      "kind": "frontispiece",
      "caption": "Allegorical frontispiece depicting the 'Magnetic Kingdom of Nature' with a central winged figure, emblems, and scientific diagrams."
    }
  ],
  "699064bdef12272ffdc9432e": [
    {
      "src": "https://images.sourcelibrary.org/gallery/699064bdef12272ffdc9432e/699064bdef12272ffdc9432f-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/699064bdef12272ffdc9432e/699064bdef12272ffdc9432f-0-thumb.jpg",
      "aspect": 0.73,
      "page": 1,
      "kind": "frontispiece",
      "caption": "Engraved frontispiece depicting Mother Shipton in a landscape, titled 'MOTHER SHIPTON'S STATUE'."
    }
  ],
  "69aec1f00767ad23dd0affb0": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b014c-0.jpg?v=1780586054285",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b014c-0-thumb.jpg?v=1780586054285",
      "aspect": 0.702,
      "page": 412,
      "kind": "diagram",
      "caption": "A systematic grid of anatomical diagrams illustrating the articulation of speech sounds, accompanied by a larger detailed cross-section of the human vocal apparatus."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0109-0.jpg?v=1781667062068",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0109-0-thumb.jpg?v=1781667062068",
      "aspect": 1.406,
      "page": 345,
      "kind": "diagram",
      "caption": "A complex diagram illustrating local prepositions, featuring a human figure standing beside a large circular structure with concentric rings and directional labels."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0affb9-0.jpg?v=1781667079270",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0affb9-0-thumb.jpg?v=1781667079270",
      "aspect": 1.04,
      "page": 9,
      "kind": "engraving",
      "caption": "Coat of arms of the Royal Society of London"
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b014a-0.jpg?v=1781667176182",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b014a-0-thumb.jpg?v=1781667176182",
      "aspect": 0.731,
      "page": 410,
      "kind": "diagram",
      "caption": "A systematic grid displaying the phonetic and semantic symbols of John Wilkins' philosophical language."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0138-0.jpg?v=1780588402447",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0138-0-thumb.jpg?v=1780588402447",
      "aspect": 0.818,
      "page": 392,
      "kind": "diagram",
      "caption": "A complex phonetic classification diagram mapping letters to the organs of speech and their articulatory properties."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0155-0.jpg?v=1781667176141",
      "thumb": "https://images.sourcelibrary.org/gallery/69aec1f00767ad23dd0affb0/69aec1f00767ad23dd0b0155-0-thumb.jpg?v=1781667176141",
      "aspect": 2.504,
      "page": 421,
      "kind": "diagram",
      "caption": "A comprehensive table of symbols representing various categories of the 'Real Character' language."
    }
  ],
  "69a5f6b11cf742c360413d42": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413de7-0.jpg?v=1788406320333",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413de7-0-thumb.jpg?v=1788406320333",
      "aspect": 0.804,
      "page": 165,
      "kind": "engraving",
      "caption": "A detailed engraving of a hydraulic milling machine featuring an Archimedean screw, a water wheel, and a grinding mill."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413de9-0.jpg?v=1788406320568",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413de9-0-thumb.jpg?v=1788406320568",
      "aspect": 0.784,
      "page": 167,
      "kind": "engraving",
      "caption": "Technical engraving of a complex hydraulic and mechanical system featuring an Archimedean screw, water wheel, and mill."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413df9-0.jpg?v=1788406321564",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413df9-0-thumb.jpg?v=1788406321564",
      "aspect": 0.807,
      "page": 183,
      "kind": "engraving",
      "caption": "Technical engraving of a mechanical sawmill with human operators and labeled components."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413dfd-0.jpg?v=1788406321897",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413dfd-0-thumb.jpg?v=1788406321897",
      "aspect": 0.771,
      "page": 187,
      "kind": "engraving",
      "caption": "A detailed technical engraving of a water-powered sawmill showing internal and external mechanics."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413dff-0.jpg?v=1788406321933",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413dff-0-thumb.jpg?v=1788406321933",
      "aspect": 0.772,
      "page": 189,
      "kind": "engraving",
      "caption": "A full-page copperplate engraving of a two-story mechanical mill powered by a horse, featuring a sawmill and a flour mill."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413e1b-0.jpg?v=1788406322352",
      "thumb": "https://images.sourcelibrary.org/gallery/69a5f6b11cf742c360413d42/69a5f6b11cf742c360413e1b-0-thumb.jpg?v=1788406322352",
      "aspect": 0.79,
      "page": 217,
      "kind": "engraving",
      "caption": "Detailed engraving of a water-powered forge with a blacksmith at work."
    }
  ],
  "6953e58d77f38f6761bf0cfc": [
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d17-0.jpg?v=1771876426582",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d17-0-thumb.jpg?v=1771876426582",
      "aspect": 0.556,
      "page": 27,
      "kind": "diagram",
      "caption": "Scientific diagram of a candle flame illustrating the propagation of light waves."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d34-0.jpg?v=1780511239074",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d34-0-thumb.jpg?v=1780511239074",
      "aspect": 1.519,
      "page": 56,
      "kind": "diagram",
      "caption": "Scientific diagram illustrating the propagation of light waves and atmospheric refraction."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d19-0.jpg?v=1771876425771",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d19-0-thumb.jpg?v=1771876425771",
      "aspect": 0.998,
      "page": 29,
      "kind": "diagram",
      "caption": "Geometric diagram illustrating the propagation of light waves from a point source."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d44-0.jpg?v=1780511238259",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d44-0-thumb.jpg?v=1780511238259",
      "aspect": 1.073,
      "page": 72,
      "kind": "diagram",
      "caption": "Scientific diagram illustrating Huygens' principle of wave propagation."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d0f-0.jpg?v=1780511237715",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d0f-0-thumb.jpg?v=1780511237715",
      "aspect": 0.371,
      "page": 19,
      "kind": "diagram",
      "caption": "Scientific diagram illustrating the determination of the speed of light via the eclipses of Jupiter's moons."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d29-0.jpg?v=1780511237527",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e58d77f38f6761bf0cfc/6953e58d77f38f6761bf0d29-0-thumb.jpg?v=1780511237527",
      "aspect": 1.213,
      "page": 45,
      "kind": "diagram",
      "caption": "Geometric diagram illustrating the refraction of light waves at a surface boundary."
    }
  ],
  "6953e50277f38f6761bef58d": [
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fa-1.jpg?v=1771876387622",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fa-1-thumb.jpg?v=1771876387622",
      "aspect": 1.584,
      "page": 109,
      "kind": "diagram",
      "caption": "Complex optical diagram involving a prism, a partial depiction of an eye, and a grid."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fe-1.jpg?v=1771876388181",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fe-1-thumb.jpg?v=1771876388181",
      "aspect": 1.343,
      "page": 113,
      "kind": "diagram",
      "caption": "Scientific diagram Fig. 14 illustrating the decomposition of light and spectral analysis."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fe-0.jpg?v=1771876388052",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef5fe-0-thumb.jpg?v=1771876388052",
      "aspect": 2.044,
      "page": 113,
      "kind": "diagram",
      "caption": "Scientific diagram Fig. 13 showing light refraction through a prism."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef708-0.jpg",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef708-0-thumb.jpg",
      "aspect": 0.508,
      "page": 379,
      "kind": "diagram",
      "caption": "A collection of eight numbered mathematical diagrams (26, 27, 29, 30, 32, 33, 35, 36) illustrating various geometric curves and their properties."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef600-0.jpg?v=1771876389550",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef600-0-thumb.jpg?v=1771876389550",
      "aspect": 0.339,
      "page": 115,
      "kind": "diagram",
      "caption": "A series of four scientific diagrams (Fig. 13-16) illustrating principles of optics, specifically the refraction of light through prisms."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef666-0.jpg?v=1771876390586",
      "thumb": "https://images.sourcelibrary.org/gallery/6953e50277f38f6761bef58d/6953e50277f38f6761bef666-0-thumb.jpg?v=1771876390586",
      "aspect": 0.561,
      "page": 217,
      "kind": "diagram",
      "caption": "A complex scientific diagram labeled Fig. 6, showing a grid with vertical lines corresponding to colors and Greek letters, intersected by numerous diagonal lines."
    }
  ],
  "69a565d45a8a09c1b325e8f2": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea24-0.jpg?v=1779930358881",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea24-0-thumb.jpg?v=1779930358881",
      "aspect": 0.728,
      "page": 306,
      "kind": "diagram",
      "caption": "A complex celestial diagram from Cellarius's Harmonia Macrocosmica illustrating planetary aspects, conjunctions, and oppositions centered on a polar projection of the Earth."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea29-0.jpg?v=1779930359022",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea29-0-thumb.jpg?v=1779930359022",
      "aspect": 0.73,
      "page": 311,
      "kind": "engraving",
      "caption": "A complex celestial diagram illustrating the theory of the Sun's motion through an eccentric orbit without an epicycle, surrounded by allegorical figures and smaller astronomical models."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea34-0.jpg?v=1779930359136",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea34-0-thumb.jpg?v=1779930359136",
      "aspect": 0.681,
      "page": 322,
      "kind": "engraving",
      "caption": "A hand-colored celestial chart from Andreas Cellarius's Harmonia Macrocosmica, illustrating the spiral motion of the sun around the Earth according to the Ptolemaic system."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea39-0.jpg?v=1779930366641",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea39-0-thumb.jpg?v=1779930366641",
      "aspect": 0.74,
      "page": 327,
      "kind": "diagram",
      "caption": "A hand-colored celestial map from Cellarius's Harmonia Macrocosmica illustrating the theory of the Moon's motion through epicycles and eccentrics."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea44-0.jpg?v=1779930367576",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea44-0-thumb.jpg?v=1779930367576",
      "aspect": 0.707,
      "page": 338,
      "kind": "diagram",
      "caption": "A hand-colored celestial map illustrating the phases of the moon and its relationship to the sun and earth, from Andreas Cellarius's Harmonia Macrocosmica."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea51-0.jpg?v=1779930366601",
      "thumb": "https://images.sourcelibrary.org/gallery/69a565d45a8a09c1b325e8f2/69a565d45a8a09c1b325ea51-0-thumb.jpg?v=1779930366601",
      "aspect": 0.72,
      "page": 351,
      "kind": "diagram",
      "caption": "A complex celestial diagram from Cellarius's Harmonia Macrocosmica illustrating the 'Theoria Trium Superiorum Planetarum' (Theory of the Three Superior Planets), showing epicycles and planetary motions within a zodiacal ring, surrounded by allegorical figures in clouds."
    }
  ],
  "69c7ac9e92b884e4f8173e9c": [
    {
      "src": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69c93660acb41c329361200a-0.jpg?v=1780515223565",
      "thumb": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69c93660acb41c329361200a-0-thumb.jpg?v=1780515223565",
      "aspect": 0.505,
      "page": 103,
      "kind": "diagram",
      "caption": "A detailed cosmological diagram showing the solar system and surrounding celestial bodies."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69f49c16e13f19e12acca3c0-0.jpg?v=1781148748275",
      "thumb": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69f49c16e13f19e12acca3c0-0-thumb.jpg?v=1781148748275",
      "aspect": 0.521,
      "page": 17,
      "kind": "diagram",
      "caption": "A complex diagram showing multiple planetary systems or 'vortices' as conceived in Cartesian physics, illustrating the plurality of worlds."
    },
    {
      "src": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69f49c05e13f19e12acca3b5-0.jpg?v=1781148748302",
      "thumb": "https://images.sourcelibrary.org/gallery/69c7ac9e92b884e4f8173e9c/69f49c05e13f19e12acca3b5-0-thumb.jpg?v=1781148748302",
      "aspect": 0.633,
      "page": 6,
      "kind": "diagram",
      "caption": "An engraving of a Copernican armillary sphere on a decorative pedestal."
    }
  ],
  "6a0a22c80eca358f15e83cf2": [
    {
      "src": "https://images.sourcelibrary.org/gallery/6a0a22c80eca358f15e83cf2/6a0a22c80eca358f15e83dd3-0.jpg?v=1780589410334",
      "thumb": "https://images.sourcelibrary.org/gallery/6a0a22c80eca358f15e83cf2/6a0a22c80eca358f15e83dd3-0-thumb.jpg?v=1780589410334",
      "aspect": 0.671,
      "page": 225,
      "kind": "diagram",
      "caption": "A vertical series of four scientific diagrams showing geological or isothermal profiles."
    }
  ]
};

export const SHELF_COVER_ASPECT: Record<string, number> = {
  "69dbca051040d1d5e20a8970": 0.719,
  "69dbcac31040d1d5e20ae6df": 0.726,
  "69dbc7d91040d1d5e2094b55": 0.747,
  "69b221fe08069e96e8431e0a": 0.751,
  "69b2ff0ea1a4246ddb45adbb": 0.788,
  "695592c17bd6d2cd1d61afec": 0.683,
  "69905ac4aaa7f10ed4cfb814": 0.737,
  "69bfcf9c3047130b1c3bfa3e": 0.685,
  "69c1b7b68522835be8448dbb": 0.757,
  "69b21cc3429e087c6f86586b": 0.751,
  "69520579ab34727b1f042cb6": 0.739,
  "69b65cf7b3f4fc0441515dbf": 0.712,
  "695aa9a4be4023bd34bd6b7d": 0.674,
  "69a5f6bf1cf742c3604142b5": 0.747,
  "69a5d8cda63a00aaae8aaae5": 1.287,
  "69b6660eb3f4fc0441558978": 0.68,
  "fb480eff2d4882dbec8defb0": 0.682,
  "6956890dbe7c607c5f03c7d9": 0.561,
  "6985ca711c89f522ebc0db71": 0.683,
  "69a5b99dd76b98f272fcec6d": 0.628,
  "695294dbb184004c526a272b": 0.617,
  "69d003fc0f4d028b337a0aec": 0.751,
  "69905cf8aaa7f10ed4cfd202": 0.552,
  "69e53747860f4574c2e71566": 1.716,
  "69b51ea29a81ef7feb3d84e3": 0.625,
  "69b1c67aedda7fb64e1a1201": 0.713,
  "69a5f6cd1cf742c3604142ea": 0.771,
  "69905d0eaaa7f10ed4cfd7bd": 0.735,
  "6a0a22ae0eca358f15e839f2": 0.601,
  "69b185aac4be2cdd0edc3e24": 0.664,
  "69b51ed847b06ecd58197576": 0.726,
  "699064bdef12272ffdc9432e": 0.638,
  "69aec1f00767ad23dd0affb0": 0.614,
  "69b6ad67dc00a90e322a9ecd": 0.636,
  "69b418ff2b0edf3eaa2de7aa": 1.505,
  "69a5f6b11cf742c360413d42": 0.694,
  "6953e58d77f38f6761bf0cfc": 0.808,
  "69b51ea547b06ecd58194b3e": 0.6,
  "69b51ea6cf111105c42a2b3f": 0.621,
  "6953e50277f38f6761bef58d": 0.744,
  "69a565d45a8a09c1b325e8f2": 0.648,
  "69a683b0256d25f4660595df": 0.644,
  "6a0a22b70eca358f15e83ab7": 0.755,
  "69b18a62c4be2cdd0edc7804": 0.538,
  "69c7ac9e92b884e4f8173e9c": 1.202,
  "698fb7976b95eeda7d2d36ac": 0.621,
  "6a0a22c80eca358f15e83cf2": 0.637,
  "6a0a22ce0eca358f15e83e15": 0.708,
  "6a0a22e80eca358f15e83e96": 0.615,
  "69a5535bbab4924e157599c3": 0.655
};

/** The library's own 150px rendition of a cover, where one exists (checked at build). */
export const SHELF_COVER_SMALL: Record<string, string> = {
  "69dbca051040d1d5e20a8970": "https://images.sourcelibrary.org/pages/69dbca051040d1d5e20a8970/0005-thumb.jpg",
  "69dbcac31040d1d5e20ae6df": "https://images.sourcelibrary.org/pages/69dbcac31040d1d5e20ae6df/0002-thumb.jpg",
  "69dbc7d91040d1d5e2094b55": "https://images.sourcelibrary.org/pages/69dbc7d91040d1d5e2094b55/0002-thumb.jpg",
  "69b221fe08069e96e8431e0a": "https://images.sourcelibrary.org/pages/69b221fe08069e96e8431e0a/0012-thumb.jpg",
  "69b2ff0ea1a4246ddb45adbb": "https://images.sourcelibrary.org/pages/69b2ff0ea1a4246ddb45adbb/0003-thumb.jpg",
  "695592c17bd6d2cd1d61afec": "https://images.sourcelibrary.org/pages/695592c17bd6d2cd1d61afec/0005-thumb.jpg",
  "69905ac4aaa7f10ed4cfb814": "https://images.sourcelibrary.org/pages/69905ac4aaa7f10ed4cfb814/0003-thumb.jpg",
  "69bfcf9c3047130b1c3bfa3e": "https://images.sourcelibrary.org/pages/69bfcf9c3047130b1c3bfa3e/0001-thumb.jpg",
  "69c1b7b68522835be8448dbb": "https://images.sourcelibrary.org/pages/69c1b7b68522835be8448dbb/0005-thumb.jpg",
  "69b21cc3429e087c6f86586b": "https://images.sourcelibrary.org/pages/69b21cc3429e087c6f86586b/0010-thumb.jpg",
  "69520579ab34727b1f042cb6": "https://images.sourcelibrary.org/pages/69520579ab34727b1f042cb6/0003-thumb.jpg",
  "69b65cf7b3f4fc0441515dbf": "https://images.sourcelibrary.org/pages/69b65cf7b3f4fc0441515dbf/0003-thumb.jpg",
  "695aa9a4be4023bd34bd6b7d": "https://images.sourcelibrary.org/pages/695aa9a4be4023bd34bd6b7d/0003-thumb.jpg",
  "69a5d8cda63a00aaae8aaae5": "https://images.sourcelibrary.org/pages/69a5d8cda63a00aaae8aaae5/0003-thumb.jpg",
  "69b6660eb3f4fc0441558978": "https://images.sourcelibrary.org/pages/69b6660eb3f4fc0441558978/0002-thumb.jpg",
  "6956890dbe7c607c5f03c7d9": "https://images.sourcelibrary.org/pages/6956890dbe7c607c5f03c7d9/0007-thumb.jpg",
  "69a5b99dd76b98f272fcec6d": "https://images.sourcelibrary.org/pages/69a5b99dd76b98f272fcec6d/0009-thumb.jpg",
  "695294dbb184004c526a272b": "https://images.sourcelibrary.org/pages/695294dbb184004c526a272b/0005-thumb.jpg",
  "69d003fc0f4d028b337a0aec": "https://images.sourcelibrary.org/pages/69d003fc0f4d028b337a0aec/0007-thumb.jpg",
  "69905cf8aaa7f10ed4cfd202": "https://images.sourcelibrary.org/pages/69905cf8aaa7f10ed4cfd202/0008-thumb.jpg",
  "69b51ea29a81ef7feb3d84e3": "https://images.sourcelibrary.org/pages/69b51ea29a81ef7feb3d84e3/0001-thumb.jpg",
  "69b1c67aedda7fb64e1a1201": "https://images.sourcelibrary.org/pages/69b1c67aedda7fb64e1a1201/0004-thumb.jpg",
  "69a5f6cd1cf742c3604142ea": "https://images.sourcelibrary.org/pages/69a5f6cd1cf742c3604142ea/0009-thumb.jpg",
  "69905d0eaaa7f10ed4cfd7bd": "https://images.sourcelibrary.org/pages/69905d0eaaa7f10ed4cfd7bd/0013-thumb.jpg",
  "6a0a22ae0eca358f15e839f2": "https://images.sourcelibrary.org/pages/6a0a22ae0eca358f15e839f2/0001-thumb.jpg",
  "69b185aac4be2cdd0edc3e24": "https://images.sourcelibrary.org/pages/69b185aac4be2cdd0edc3e24/0009-thumb.jpg",
  "69b51ed847b06ecd58197576": "https://images.sourcelibrary.org/pages/69b51ed847b06ecd58197576/0007-thumb.jpg",
  "699064bdef12272ffdc9432e": "https://images.sourcelibrary.org/pages/699064bdef12272ffdc9432e/0003-thumb.jpg",
  "69aec1f00767ad23dd0affb0": "https://images.sourcelibrary.org/pages/69aec1f00767ad23dd0affb0/0009-thumb.jpg",
  "69b6ad67dc00a90e322a9ecd": "https://images.sourcelibrary.org/pages/69b6ad67dc00a90e322a9ecd/0007-thumb.jpg",
  "69b418ff2b0edf3eaa2de7aa": "https://images.sourcelibrary.org/pages/69b418ff2b0edf3eaa2de7aa/0002-thumb.jpg",
  "69a5f6b11cf742c360413d42": "https://images.sourcelibrary.org/pages/69a5f6b11cf742c360413d42/0005-thumb.jpg",
  "6953e58d77f38f6761bf0cfc": "https://images.sourcelibrary.org/pages/6953e58d77f38f6761bf0cfc/0005-thumb.jpg",
  "69b51ea547b06ecd58194b3e": "https://images.sourcelibrary.org/pages/69b51ea547b06ecd58194b3e/0005-thumb.jpg",
  "69b51ea6cf111105c42a2b3f": "https://images.sourcelibrary.org/pages/69b51ea6cf111105c42a2b3f/0003-thumb.jpg",
  "6953e50277f38f6761bef58d": "https://images.sourcelibrary.org/pages/6953e50277f38f6761bef58d/0009-thumb.jpg",
  "69a565d45a8a09c1b325e8f2": "https://images.sourcelibrary.org/pages/69a565d45a8a09c1b325e8f2/0009-thumb.jpg",
  "69a683b0256d25f4660595df": "https://images.sourcelibrary.org/pages/69a683b0256d25f4660595df/0005-thumb.jpg",
  "6a0a22b70eca358f15e83ab7": "https://images.sourcelibrary.org/pages/6a0a22b70eca358f15e83ab7/0003-thumb.jpg",
  "69b18a62c4be2cdd0edc7804": "https://images.sourcelibrary.org/pages/69b18a62c4be2cdd0edc7804/0005-thumb.jpg",
  "69c7ac9e92b884e4f8173e9c": "https://images.sourcelibrary.org/pages/69c7ac9e92b884e4f8173e9c/0002-thumb.jpg",
  "698fb7976b95eeda7d2d36ac": "https://images.sourcelibrary.org/pages/698fb7976b95eeda7d2d36ac/0007-thumb.jpg",
  "6a0a22c80eca358f15e83cf2": "https://images.sourcelibrary.org/pages/6a0a22c80eca358f15e83cf2/0001-thumb.jpg",
  "6a0a22ce0eca358f15e83e15": "https://images.sourcelibrary.org/pages/6a0a22ce0eca358f15e83e15/0001-thumb.jpg",
  "6a0a22e80eca358f15e83e96": "https://images.sourcelibrary.org/pages/6a0a22e80eca358f15e83e96/0003-thumb.jpg",
  "69a5535bbab4924e157599c3": "https://images.sourcelibrary.org/pages/69a5535bbab4924e157599c3/0005-thumb.jpg"
};
